module.exports = {
  /* common */
  ERROR: 'Internal server error',
  NOT_ALLOWED_TO_LOGIN_FROM_MOBILE: 'User account is not registered',
  NOT_ALLOWED_TO_LOGIN_FROM_ADMINPANEL: 'Client account is not registered',
  TYPE_NOT_DEFINED: 'Type is not defined',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  SUCCESS: 'Success',
  NO_DATA_FOUND: 'No data found',
  UNAUTHORIZED_ACCESS: 'Unauthorized access',

  /**User */
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  PASSWORD_NOT_MATCHED: 'Password not matched',
  ADMIN_REGISTER_SUCCESS: 'Admin register successfully',
  ADMIN_REGISTER_FAILED: 'Admin register failed',
  INVALID_FIRSTNAME: 'Invalid first name',
  INVALID_LASTNAME: 'Invalid last name',
  INVALID_EMAIL: 'Invalid email',
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_UPDATED_SUCCESSFULLY: 'User updated successfully',
  INVALID_TOKEN: 'Invalid token',
  EMPTY_EMAIL: 'Email is required',
  INVALID_PHONE_NUMBER_FORMAT: 'Invalid contact number format',
  EMPTY_PHONE_NUMBER: 'Contact number is required',
  INVALID_PHONE_NUMBER: 'Invalid contact number',
  PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters',
  PASSWORD_REGEX: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[a-zA-Z\d@$.!%*#?&]/,
  INVALID_PASSWORD:
    'Password must contain at least one uppercase letter, one lowercase letter, one number and one special character',
  PASSWORD_MISMATCH: 'Password mismatch',
  LOGIN_SUCCESS: 'Login successfully',
  USER_NOT_REGISTERED: 'User is not registered',
  RESTRICTED_EMAIL_UPDATE: 'Email update is restricted',
  FORGOT_PASSWORD_SUCCESS: 'Reset password link sent to your email',
  TOKEN_EXPIRED: 'Token expired',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
  INVALID_UUID: 'Invalid uuid',
  UUId_VERIFIED: 'Uuid verified successfully',
  INVALID_UId_VERIFIED: 'Uid not verified',
  USER_NOT_FOUND: 'User not found',
  USER_ALREADY_EXIST: 'User already exist',
  USER_CREATED: 'User created successfully',
  PAN_CARD_NUMBER_ALREADY_EXISTS: 'Pan card number already exists',
  USER_RETRIVED_SUCCESSFULLY: 'User retrived successfully',

  /**AI */
  CONTENT_TYPE_ERROR: 'Content type must be application/json',
  CATEGORY_TYPE_ERROR: 'Category type must be string',
  AI_RETRIVED_SUCCESSFULLY: 'AI retrived successfully',
  AI_REGISTER_SUCCESSFULLY: 'AI registered successfully',
  AI_UPDATED_SUCCESSFULLY: 'AI updated successfully',

  /**Config */
  PROFILE_CONFIG_RETRIVE_SUCCESSFULLY: 'Profile Config retrived successfully',

  /** Config screens id */
  PROFILE_SCREEN_ID: 'profile_01',
  ELECTRICITY_SCREEN_ID: 'electricity_02',
  EMI_SCREEN_ID: 'emi_03',
  INSURANCE_SCREEN_ID: 'insurance_04',
  FASTAG_SCREEN_ID: 'fastag_05',
  POSTPAID_SCREEN_ID: 'postpaid_06',
  LANDLINE_SCREEN_ID: 'landline_07',
  BROADBAND_SCREEN_ID: 'broadband_08',
  CABLE_SCREEN_ID: 'cable_09',
  DTH_SCREEN_ID: 'dth_10',
  GAS_SCREEN_ID: 'gas_11',
  LPG_SCREEN_ID: 'lpg_12',
  MUNCIPALITY_SCREEN_ID: 'muncipality_13',

  /** Config fields type */
  TEXT_TYPE: 'text',
  NUMBER_TYPE: 'number',
  MOBILE_FIELD_TYPE: 'mobile',
  EMAIL_TYPE: 'email',
  DATETIME_TYPE: 'dateTime',
  DATE_TYPE: 'date',
  DROPDOWN_TYPE: 'dropdown',
  CHECKBOX_TYPE: 'checkbox',
  RADIO_BUTTON: 'radioButton',
  BOOLEAN_TYPE: 'boolean',
  TERMS_AND_CONDITIONS: 'termsAndConditions',

  /** Config screen id */
  HOME_LOAN_SCREEN_ID: 'homeLoan_01',
  PERSONAL_LOAN_SCREEN_ID: 'personalLoan_02',
  CAR_LOAN_SCREEN_ID: 'carLoan_03',
  BUSINESS_LOAN_SCREEN_ID: 'businessLoan_04',
  CREDIT_CARD_SCREEN_ID: 'creditCard_05',

  /** Pay Sprint credentials */
  PAYSPRINT_CLIENT_ID: 'client_01',
  PAYSPRINT_AUTHORIZATION_KEY: process.env.PAYSPRINT_AUTHORIZATION_KEY,

  /** Bill payment */
  BILL_PAYMENT_SUCCESSFULLY: 'Bill payment successfully',
  BILL_PAYMENT_FAILED: 'Bill payment failed',
  BILL_PAYMENT_RETRIVED_SUCCESSFULLY: 'Bill payment retrived successfully',
  BILL_PAYMENT_RETRIVED_FAILED: 'Bill payment retrived failed',
  INVALID_OPERATOR: 'Invalid operator',
  INVALID_CA_NUMBER: 'Invalid ca number',
  BILL_CATEGORY: [
    'Broadband',
    'Electricity',
    'Gas',
    'Insurance',
    'Water',
    'PREPAID',
    'Postpaid',
    'DTH',
    'Landline',
    'Cable',
    'Fastag',
    'LPG',
    'Municipality',
  ],
  INVALID_BILL_CATEGORY: 'Invalid bill category',
  BILL_OPERATOR_RETRIVED_SUCCESSFULLY: 'Bill operator retrived successfully',

  /** Electicity Bill */
  ELECTRICITY_BILL_PAYMENT_SUCCESS: 'Electricity bill payment successfully',
  ELECTRICITY_BILL_PAYMENT_FAILED: 'Electricity bill payment failed',
  ELECTRICITY_BILL_PAYMENT_RETRIVED_SUCCESSFULLY: 'Electricity bill payment retrived successfully',
  ELECTRICITY_BILL_PAYMENT_RETRIVED_FAILED: 'Electricity bill payment retrived failed',
  ELECTRICITY_BILL_OPERATOR_RETRIVED_SUCCESSFULLY:
    'Electricity bill operator retrived successfully',
  ELECTRICITY_BILL_CONFIG_RETRIVED_SUCCESSFULLY: 'Electricity bill config retrived successfully',

  /** Bill payment Types */
  ELECTRICITY: 'Electricity',
  GAS: 'Gas',
  WATER: 'Water',
  TELEPHONE: 'Telephone',
  INTERNET: 'Internet',
  TV: 'TV',
  EDUCATION: 'Education',
  INSURANCE: 'Insurance',
  CREDIT_CARD: 'Credit Card',
  LOAN: 'Loan',

  // TERMS AND CONDITIONS
  LOAN_TERMS_AND_CONDITIONS:
    ' I hereby appoint Finvibes Financial Services Pvt Ltd as my athorised represantative to receive my credit information from experin or such credit bureaus. I hereby irrevicably and unconditionallly consent to such credit information being provide by experian or such credit bureaus at my registered email id and also through my fundingindia.in account as per my independent registration with them',

  PLEASE_ACCEPT_TERMS_AND_CONDITIONS: 'Please accept terms and conditions',

  /** Loan form  validation*/
  INVALID_MOBILE_NUMBER: 'Invalid mobile number',
  PHONE_NUMBER_INVALID_LENGTH: 'Invalid mobile number length, should be 10 digit',
  INVALID_PAN_CARD: 'Invalid pan card number',
  INVALID_PIN_CODE: 'Invalid pin code',
  INVALID_LOAN_AMOUNT: 'Invalid loan amount',
  INVALID_EMPLOYMENT_TYPE: 'Invalid employment type',
  INVALID_LOAN_TYPE: 'Invalid loan type',
  INVALID_CURRENT_EMI: 'Invalid current emi',
  INVALID_ZIPCODE: 'Invalid zipcode',
  INVALID_DOB: 'Invalid date of birth',
  INVALID_TERMS_AND_CONDITIONS: 'Invalid terms and conditions',
  LOAN_STATUS: ['open', 'close'],
  INVALID_LOAN_STATUS: 'Invalid loan status',
  SOURCE_OF_LEAD: ['Direct Offline', 'Direct Online', 'IMD Channel', null],
  INVALID_LEAD_SOURCE: 'Invalid lead source',
  CURRENT_STATUS: [
    'Document Verification',
    'Application Submitted',
    'Pending with Credit',
    'Offer Received',
    'Offer Selected',
    'Loan Sanctioned',
    'Disbursement Documentation',
    'Disbursement',
    'Amount Credited/Cheque issued',
    null,
  ],
  INVALID_CURRENT_STATUS: 'Invalid current status',

  /** Loan form messages */
  LOAN_FORM_SUBMITTED_SUCCESSFULLY: 'Loan form submitted successfully',
  LOAN_FORM_SUBMITTED_FAILED: 'Loan form submitted failed',
  LOAN_FORM_RETRIVED_SUCCESSFULLY: 'Loan form retrived successfully',
  LOAN_FORM_RETRIVED_FAILED: 'Loan form retrived failed',
  LOAN_FORM_UPDATED_SUCCESSFULLY: 'Loan form updated successfully',

  /** Bank Opening*/
  IP_ADDRESS_RETRIVED_SUCCESSFULLY: 'Ip address retrived successfully',
  BANK_OPENING_SUCCESSFULLY: 'Bank open successfully',
  INVALID_BENEFICIARY_NAME: 'Invalid beneficiary name',
  INVALID_BENEFICIARY_EMAIL: 'Invalid beneficiary email',
  INVALID_BENEFICIARY_MOBILE_NO: 'Invalid beneficiary mobile no',
  INVALID_LENGTH_BENEFICIARY_PAN: 'Invalid length beneficiary pan, should be 12 digit',
  INVALID_LENGTH_BENEFICIARY_ADHAR: 'Invalid length beneficiary adhar, should be 12 digit',
  INVALID_BANK_OPENING_CATEGORY: 'Invalid bank opening category',
  INVALID_BANK_OPENING_NAME: 'Invalid bank opening name',
  BANK_SERVER_DOWN: 'Bank server down',
  BANK_OPENING_FORM_RETRIVED_SUCCESSFULLY: 'Bank opening form retrived successfully',

  // Bank Name
  KOTAK: 'Kotak',
  AU: 'AU',
  INDUSIND: 'indusind',

  // Bank Opening Category
  SAVING: 'Saving',
  CREDIT: 'Credit',

  // Bank CRUD constants
  BANK_ALREADY_EXISTS: 'Bank already exists',
  BANK_CREATE_SUCCESS: 'Bank created successfully',
  BANK_CREATE_FAILED: 'Bank creation failed',
  BANK_UPDATE_SUCCESS: 'Bank updated successfully',
  BANK_UPDATE_FAILED: 'Bank updation failed',
  BANK_DELETE_SUCCESS: 'Bank deleted successfully',
  BANK_DELETE_FAILED: 'Bank deletion failed',
  BANK_NOT_FOUND: 'Bank not found',
  BANK_ALREADY_DELETED: 'Bank already deleted',
  BANK_ALREADY_ACTIVE: 'Bank already active',
  BANK_ALREADY_INACTIVE: 'Bank already inactive',
  BANK_FETCH_SUCCESS: 'Bank fetched successfully',
  BANK_FETCH_FAILED: 'Bank fetch failed',
  INVALID_BANK: 'Invalid bank',

  // Code CRUD constants
  CODE_ALREADY_EXISTS: 'Code already exists',
  CODE_CREATE_SUCCESS: 'Code created successfully',
  CODE_CREATE_FAILED: 'Code creation failed',
  CODE_UPDATE_SUCCESS: 'Code updated successfully',
  CODE_UPDATE_FAILED: 'Code updation failed',
  CODE_DELETE_SUCCESS: 'Code deleted successfully',
  CODE_DELETE_FAILED: 'Code deletion failed',
  CODE_NOT_FOUND: 'Code not found',
  CODE_ALREADY_DELETED: 'Code already deleted',
  CODE_ALREADY_ACTIVE: 'Code already active',
  CODE_ALREADY_INACTIVE: 'Code already inactive',
  CODE_FETCH_SUCCESS: 'Code fetched successfully',
  CODE_FETCH_FAILED: 'Code fetch failed',
  INVALID_CODES: 'Invalid codes',
};
